version: '3.8'

services:
  auth:
    build: .
    ports:
      - "8012:8012"
    env_file:
      - .env
    depends_on:
      - postgresql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8012/health"]
      interval: 30s
      timeout: 4s
      retries: 3
    restart: unless-stopped
    networks:
      - air-network

  postgresql:
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 30s
    networks:
      - air-network

networks:
  air-network:
    driver: bridge